{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agi-synapse.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agi-synapse.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.global.workloadIdentity.enabled (not .Values.serviceAccount.annotations) }}
    iam.gke.io/gcp-service-account: {{ .Values.global.workloadIdentity.gcpServiceAccount | quote }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
