"""Monitoring, observability, and metrics package."""

from monitoring.metrics import (
    ACTIVE_MEMORY_VECTORS,
    FAISS_QUERY_LATENCY_SECONDS,
    MODEL_RELOAD_ATTEMPTS_TOTAL,
    MYSQL_BUFFER_QUEUE_SIZE,
    PAPERS_INGESTED_TOTAL,
    REACT_STEP_LATENCY_SECONDS,
    SYSTEM_RAM_USAGE_BYTES,
    SYSTEM_VRAM_USAGE_BYTES,
    TIME_TO_FIRST_TOKEN_SECONDS,
    TOKENS_PER_SECOND,
    TOOL_EXECUTION_CALLS_TOTAL,
    get_latest_metrics,
    record_model_reload,
    record_paper_ingested,
    record_tool_call,
    time_faiss_query,
    time_react_step,
    update_system_gauges,
)

__all__ = [
    "PAPERS_INGESTED_TOTAL",
    "TOOL_EXECUTION_CALLS_TOTAL",
    "MODEL_RELOAD_ATTEMPTS_TOTAL",
    "REACT_STEP_LATENCY_SECONDS",
    "TIME_TO_FIRST_TOKEN_SECONDS",
    "TOKENS_PER_SECOND",
    "FAISS_QUERY_LATENCY_SECONDS",
    "ACTIVE_MEMORY_VECTORS",
    "MYSQL_BUFFER_QUEUE_SIZE",
    "SYSTEM_RAM_USAGE_BYTES",
    "SYSTEM_VRAM_USAGE_BYTES",
    "get_latest_metrics",
    "record_paper_ingested",
    "record_tool_call",
    "record_model_reload",
    "time_react_step",
    "time_faiss_query",
    "update_system_gauges",
]
